"""Persistence repositories."""

from coder_manager.repositories.instance_kubernetes import (
    InstanceKubernetesAlreadyConfiguredError,
    InstanceKubernetesImmutableFieldError,
    InstanceKubernetesNotFoundError,
    InstanceKubernetesRepository,
)
from coder_manager.repositories.instances import (
    InstanceActionConflictError,
    InstanceAlreadyExistsError,
    InstanceDatabaseUnavailableError,
    InstanceNotFoundError,
    InstanceRepository,
    InvalidInstanceActionError,
)
from coder_manager.repositories.job_executions import (
    JobExecutionNotFoundError,
    JobExecutionRepository,
    add_job_execution,
)
from coder_manager.repositories.managed_databases import (
    DatabaseAlreadyExistsError,
    DatabaseCapacityConflictError,
    DatabaseInUseError,
    DatabaseNotFoundError,
    DatabaseRepository,
    DatabaseUsage,
)
from coder_manager.repositories.members import (
    InvalidMemberActionError,
    MemberActionConflictError,
    MemberAlreadyExistsError,
    MemberHasWorkspacesError,
    MemberInstanceBusyError,
    MemberInstanceNotFoundError,
    MemberNotFoundError,
    MemberRepository,
)
from coder_manager.repositories.template_images import (
    TemplateImageAlreadyExistsError,
    TemplateImageInUseError,
    TemplateImageNotFoundError,
    TemplateImageRepository,
    TemplateImageTemplateNotFoundError,
)
from coder_manager.repositories.templates import (
    TemplateAlreadyExistsError,
    TemplateHasWorkspacesError,
    TemplateNotFoundError,
    TemplateRepository,
    TemplateSyncInProgressError,
    TemplateWorkspaceCompatibilityError,
)
from coder_manager.repositories.workspaces import (
    InvalidWorkspaceActionError,
    WorkspaceActionConflictError,
    WorkspaceAlreadyExistsError,
    WorkspaceBusyError,
    WorkspaceConfigurationError,
    WorkspaceImageNotFoundError,
    WorkspaceImageUnavailableError,
    WorkspaceInstanceBusyError,
    WorkspaceInstanceNotFoundError,
    WorkspaceMemberNotFoundError,
    WorkspaceMemberUnavailableError,
    WorkspaceNotFoundError,
    WorkspaceRepository,
    WorkspaceTemplateNotFoundError,
    WorkspaceTemplateUnavailableError,
)

__all__ = [
    "DatabaseAlreadyExistsError",
    "DatabaseCapacityConflictError",
    "DatabaseInUseError",
    "DatabaseNotFoundError",
    "DatabaseRepository",
    "DatabaseUsage",
    "InstanceActionConflictError",
    "InstanceAlreadyExistsError",
    "InstanceDatabaseUnavailableError",
    "InstanceKubernetesAlreadyConfiguredError",
    "InstanceKubernetesImmutableFieldError",
    "InstanceKubernetesNotFoundError",
    "InstanceKubernetesRepository",
    "InstanceNotFoundError",
    "InstanceRepository",
    "InvalidInstanceActionError",
    "InvalidMemberActionError",
    "InvalidWorkspaceActionError",
    "JobExecutionNotFoundError",
    "JobExecutionRepository",
    "MemberActionConflictError",
    "MemberAlreadyExistsError",
    "MemberHasWorkspacesError",
    "MemberInstanceBusyError",
    "MemberInstanceNotFoundError",
    "MemberNotFoundError",
    "MemberRepository",
    "TemplateAlreadyExistsError",
    "TemplateHasWorkspacesError",
    "TemplateImageAlreadyExistsError",
    "TemplateImageInUseError",
    "TemplateImageNotFoundError",
    "TemplateImageRepository",
    "TemplateImageTemplateNotFoundError",
    "TemplateNotFoundError",
    "TemplateRepository",
    "TemplateSyncInProgressError",
    "TemplateWorkspaceCompatibilityError",
    "WorkspaceActionConflictError",
    "WorkspaceAlreadyExistsError",
    "WorkspaceBusyError",
    "WorkspaceConfigurationError",
    "WorkspaceImageNotFoundError",
    "WorkspaceImageUnavailableError",
    "WorkspaceInstanceBusyError",
    "WorkspaceInstanceNotFoundError",
    "WorkspaceMemberNotFoundError",
    "WorkspaceMemberUnavailableError",
    "WorkspaceNotFoundError",
    "WorkspaceRepository",
    "WorkspaceTemplateNotFoundError",
    "WorkspaceTemplateUnavailableError",
    "add_job_execution",
]
