"""Remove persisted instance URLs.

Revision ID: 0c9511e7a258
Revises: a868aa80dbea
Create Date: 2026-08-22 16:28:24.174254
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0c9511e7a258"
down_revision: str | None = "a868aa80dbea"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Remove the obsolete URL snapshot and its uniqueness constraint."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_instances_instance_url"), "instances", type_="unique")
    op.drop_column("instances", "instance_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Restore URL storage only when no instance value would need reconstruction."""

    op.execute(
        sa.text(
            """
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM instances) THEN
                    RAISE EXCEPTION
                        'Cannot restore persisted instance URLs while instances exist';
                END IF;
            END
            $$
            """
        )
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "instances",
        sa.Column(
            "instance_url",
            sa.VARCHAR(length=2048),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_unique_constraint(
        op.f("uq_instances_instance_url"),
        "instances",
        ["instance_url"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
