"""replace provider configuration with kubeconfig upload

Revision ID: 0e589bb8796e
Revises: 20260724_0003
Create Date: 2026-07-24 23:01:57.694455
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0e589bb8796e"
down_revision: str | None = "20260724_0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Discard legacy providers and replace their fields with encrypted kubeconfigs."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("DELETE FROM instance_kubernetes"))
    op.add_column(
        "instance_kubernetes",
        sa.Column("kubeconfig_enc", sa.LargeBinary(), nullable=False),
    )
    op.drop_column("instance_kubernetes", "ca")
    op.drop_column("instance_kubernetes", "host")
    op.drop_column("instance_kubernetes", "namespace")
    op.drop_column("instance_kubernetes", "token_enc")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Discard uploaded kubeconfigs and restore the legacy provider fields."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("DELETE FROM instance_kubernetes"))
    op.add_column(
        "instance_kubernetes",
        sa.Column("token_enc", sa.LargeBinary(), nullable=False),
    )
    op.add_column(
        "instance_kubernetes",
        sa.Column("namespace", sa.String(length=63), nullable=False),
    )
    op.add_column(
        "instance_kubernetes",
        sa.Column("host", sa.String(length=2048), nullable=False),
    )
    op.add_column(
        "instance_kubernetes",
        sa.Column("ca", sa.Text(), nullable=False),
    )
    op.create_check_constraint(
        op.f("ck_instance_kubernetes_ca_not_empty"),
        "instance_kubernetes",
        "length(trim(ca)) > 0",
    )
    op.create_check_constraint(
        op.f("ck_instance_kubernetes_host_not_empty"),
        "instance_kubernetes",
        "length(trim(host)) > 0",
    )
    op.create_check_constraint(
        op.f("ck_instance_kubernetes_namespace_not_empty"),
        "instance_kubernetes",
        "length(trim(namespace)) > 0",
    )
    op.drop_column("instance_kubernetes", "kubeconfig_enc")
    # ### end Alembic commands ###
