"""initial schema

Revision ID: 20260724_0001
Revises:
Create Date: 2026-07-24 09:11:19.207663
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260724_0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create the complete CoderManager schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "databases",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("instance_max", sa.Integer(), nullable=False),
        sa.Column("host", sa.String(length=255), nullable=False),
        sa.Column("port", sa.Integer(), server_default="5432", nullable=False),
        sa.Column("database_name", sa.String(length=255), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("password_enc", sa.LargeBinary(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("instance_max > 0", name=op.f("ck_databases_instance_max_positive")),
        sa.CheckConstraint(
            "length(trim(database_name)) > 0", name=op.f("ck_databases_database_name_not_empty")
        ),
        sa.CheckConstraint("length(trim(host)) > 0", name=op.f("ck_databases_host_not_empty")),
        sa.CheckConstraint("length(trim(name)) > 0", name=op.f("ck_databases_name_not_empty")),
        sa.CheckConstraint(
            "length(trim(username)) > 0", name=op.f("ck_databases_username_not_empty")
        ),
        sa.CheckConstraint("port >= 1 AND port <= 65535", name=op.f("ck_databases_port_valid")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_databases")),
    )
    op.create_index(
        "uq_databases_name_ci", "databases", [sa.literal_column("lower(name)")], unique=True
    )
    op.create_table(
        "job_executions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("task_name", sa.String(length=255), nullable=False),
        sa.Column("resource_type", sa.String(length=64), nullable=True),
        sa.Column("resource_id", sa.Uuid(), nullable=True),
        sa.Column("step", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "running", "success", "error", name="job_status"),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("attempt", sa.Integer(), server_default="0", nullable=False),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("attempt >= 0", name=op.f("ck_job_executions_attempt_non_negative")),
        sa.CheckConstraint("length(trim(name)) > 0", name=op.f("ck_job_executions_name_not_empty")),
        sa.CheckConstraint("length(trim(step)) > 0", name=op.f("ck_job_executions_step_not_empty")),
        sa.CheckConstraint(
            "length(trim(task_name)) > 0", name=op.f("ck_job_executions_task_name_not_empty")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_executions")),
    )
    op.create_index(
        "ix_job_executions_retry", "job_executions", ["status", "claimed_at"], unique=False
    )
    op.create_table(
        "templates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("scope", sa.Enum("global", "application", name="template_scope"), nullable=False),
        sa.Column("application", sa.String(length=255), nullable=True),
        sa.Column("git_url", sa.String(length=2048), nullable=False),
        sa.Column("modules", sa.JSON(), nullable=False),
        sa.Column("version", sa.String(length=255), nullable=False),
        sa.Column("min_cpu_count", sa.Integer(), nullable=False),
        sa.Column("max_cpu_count", sa.Integer(), nullable=False),
        sa.Column("min_ram_gb", sa.Integer(), nullable=False),
        sa.Column("max_ram_gb", sa.Integer(), nullable=False),
        sa.Column("min_disk_gb", sa.Integer(), nullable=False),
        sa.Column("max_disk_gb", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(scope = 'global' AND application IS NULL) OR "
            "(scope = 'application' AND application IS NOT NULL)",
            name=op.f("ck_templates_scope_application_consistent"),
        ),
        sa.CheckConstraint(
            "application IS NULL OR "
            "(length(trim(application)) > 0 AND application = upper(trim(application)))",
            name=op.f("ck_templates_application_normalized"),
        ),
        sa.CheckConstraint(
            "length(trim(git_url)) > 0", name=op.f("ck_templates_git_url_not_empty")
        ),
        sa.CheckConstraint("length(trim(name)) > 0", name=op.f("ck_templates_name_not_empty")),
        sa.CheckConstraint(
            "length(trim(version)) > 0", name=op.f("ck_templates_version_not_empty")
        ),
        sa.CheckConstraint("max_cpu_count > 0", name=op.f("ck_templates_max_cpu_count_positive")),
        sa.CheckConstraint("max_disk_gb > 0", name=op.f("ck_templates_max_disk_gb_positive")),
        sa.CheckConstraint("max_ram_gb > 0", name=op.f("ck_templates_max_ram_gb_positive")),
        sa.CheckConstraint(
            "min_cpu_count <= max_cpu_count", name=op.f("ck_templates_cpu_range_valid")
        ),
        sa.CheckConstraint("min_cpu_count > 0", name=op.f("ck_templates_min_cpu_count_positive")),
        sa.CheckConstraint(
            "min_disk_gb <= max_disk_gb", name=op.f("ck_templates_disk_range_valid")
        ),
        sa.CheckConstraint("min_disk_gb > 0", name=op.f("ck_templates_min_disk_gb_positive")),
        sa.CheckConstraint("min_ram_gb <= max_ram_gb", name=op.f("ck_templates_ram_range_valid")),
        sa.CheckConstraint("min_ram_gb > 0", name=op.f("ck_templates_min_ram_gb_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_templates")),
    )
    op.create_index(op.f("ix_templates_application"), "templates", ["application"], unique=False)
    op.create_index(
        "uq_templates_application_name_ci",
        "templates",
        ["application", sa.literal_column("lower(name)")],
        unique=True,
        postgresql_where=sa.text("scope = 'application'"),
        sqlite_where=sa.text("scope = 'application'"),
    )
    op.create_index(
        "uq_templates_global_name_ci",
        "templates",
        [sa.literal_column("lower(name)")],
        unique=True,
        postgresql_where=sa.text("scope = 'global'"),
        sqlite_where=sa.text("scope = 'global'"),
    )
    op.create_table(
        "instances",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("application", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=12), nullable=True),
        sa.Column(
            "environment",
            sa.Enum("development", "staging", "production", name="instance_environment"),
            nullable=False,
        ),
        sa.Column("action", sa.String(length=255), server_default="creating", nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "running", "success", "error", name="instance_status"),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("instance_url", sa.String(length=2048), nullable=False),
        sa.Column("password_enc", sa.LargeBinary(), nullable=True),
        sa.Column("argocd_application_name", sa.String(length=63), nullable=True),
        sa.Column("job_id", sa.Uuid(), nullable=True),
        sa.Column("step", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "application = upper(trim(application))",
            name=op.f("ck_instances_application_normalized"),
        ),
        sa.CheckConstraint("length(trim(action)) > 0", name=op.f("ck_instances_action_not_empty")),
        sa.CheckConstraint(
            "length(trim(application)) > 0", name=op.f("ck_instances_application_not_empty")
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["job_executions.id"],
            name=op.f("fk_instances_job_id_job_executions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_instances")),
        sa.UniqueConstraint(
            "application", "environment", name="uq_instances_application_environment"
        ),
        sa.UniqueConstraint(
            "argocd_application_name", name=op.f("uq_instances_argocd_application_name")
        ),
        sa.UniqueConstraint("instance_url", name="uq_instances_instance_url"),
        sa.UniqueConstraint("slug", name="uq_instances_slug"),
    )
    op.create_index(op.f("ix_instances_application"), "instances", ["application"], unique=False)
    op.create_index(op.f("ix_instances_job_id"), "instances", ["job_id"], unique=False)
    op.create_table(
        "template_images",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("template_id", sa.Uuid(), nullable=False),
        sa.Column("registry", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("version", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(trim(name)) > 0", name=op.f("ck_template_images_name_not_empty")
        ),
        sa.CheckConstraint(
            "length(trim(registry)) > 0", name=op.f("ck_template_images_registry_not_empty")
        ),
        sa.CheckConstraint(
            "length(trim(version)) > 0", name=op.f("ck_template_images_version_not_empty")
        ),
        sa.CheckConstraint(
            "name = lower(trim(name))", name=op.f("ck_template_images_name_normalized")
        ),
        sa.CheckConstraint(
            "registry = lower(trim(registry))", name=op.f("ck_template_images_registry_normalized")
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["templates.id"],
            name=op.f("fk_template_images_template_id_templates"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_template_images")),
        sa.UniqueConstraint(
            "template_id", "registry", "name", "version", name="uq_template_images_reference"
        ),
    )
    op.create_index(
        op.f("ix_template_images_template_id"), "template_images", ["template_id"], unique=False
    )
    op.create_table(
        "database_allocations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("database_id", sa.Uuid(), nullable=False),
        sa.Column("instance_id", sa.Uuid(), nullable=False),
        sa.Column("schema_name", sa.String(length=63), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(trim(schema_name)) > 0",
            name=op.f("ck_database_allocations_schema_name_not_empty"),
        ),
        sa.ForeignKeyConstraint(
            ["database_id"],
            ["databases.id"],
            name=op.f("fk_database_allocations_database_id_databases"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["instance_id"],
            ["instances.id"],
            name=op.f("fk_database_allocations_instance_id_instances"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_database_allocations")),
        sa.UniqueConstraint(
            "database_id", "schema_name", name="uq_database_allocations_database_schema"
        ),
        sa.UniqueConstraint("instance_id", name="uq_database_allocations_instance_id"),
    )
    op.create_index(
        op.f("ix_database_allocations_database_id"),
        "database_allocations",
        ["database_id"],
        unique=False,
    )
    op.create_table(
        "instance_kubernetes",
        sa.Column("instance_id", sa.Uuid(), nullable=False),
        sa.Column("host", sa.String(length=2048), nullable=False),
        sa.Column("namespace", sa.String(length=63), nullable=False),
        sa.Column("token_enc", sa.LargeBinary(), nullable=False),
        sa.Column("ca", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(trim(ca)) > 0", name=op.f("ck_instance_kubernetes_ca_not_empty")
        ),
        sa.CheckConstraint(
            "length(trim(host)) > 0", name=op.f("ck_instance_kubernetes_host_not_empty")
        ),
        sa.CheckConstraint(
            "length(trim(namespace)) > 0", name=op.f("ck_instance_kubernetes_namespace_not_empty")
        ),
        sa.ForeignKeyConstraint(
            ["instance_id"],
            ["instances.id"],
            name=op.f("fk_instance_kubernetes_instance_id_instances"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("instance_id", name=op.f("pk_instance_kubernetes")),
    )
    op.create_table(
        "members",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("instance_id", sa.Uuid(), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("role", sa.Enum("user", "admin", name="member_role"), nullable=False),
        sa.Column("action", sa.String(length=255), server_default="creating", nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "running", "success", "error", name="member_status"),
            server_default="pending",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("length(trim(action)) > 0", name=op.f("ck_members_action_not_empty")),
        sa.CheckConstraint(
            "length(trim(username)) > 0", name=op.f("ck_members_username_not_empty")
        ),
        sa.CheckConstraint(
            "username = lower(trim(username))", name=op.f("ck_members_username_normalized")
        ),
        sa.ForeignKeyConstraint(
            ["instance_id"],
            ["instances.id"],
            name=op.f("fk_members_instance_id_instances"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_members")),
        sa.UniqueConstraint("instance_id", "username", name="uq_members_instance_username"),
    )
    op.create_index(op.f("ix_members_instance_id"), "members", ["instance_id"], unique=False)
    op.create_table(
        "workspaces",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("instance_id", sa.Uuid(), nullable=False),
        sa.Column("template_id", sa.Uuid(), nullable=False),
        sa.Column("member_id", sa.Uuid(), nullable=False),
        sa.Column("image_id", sa.Uuid(), nullable=False),
        sa.Column("modules", sa.JSON(), nullable=False),
        sa.Column("cpu", sa.Integer(), nullable=False),
        sa.Column("ram", sa.Integer(), nullable=False),
        sa.Column("disk", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(length=255), server_default="creating", nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "running", "success", "error", name="workspace_status"),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("job_id", sa.Uuid(), nullable=True),
        sa.Column("step", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("cpu > 0", name=op.f("ck_workspaces_cpu_positive")),
        sa.CheckConstraint("disk > 0", name=op.f("ck_workspaces_disk_positive")),
        sa.CheckConstraint("length(trim(action)) > 0", name=op.f("ck_workspaces_action_not_empty")),
        sa.CheckConstraint("length(trim(name)) > 0", name=op.f("ck_workspaces_name_not_empty")),
        sa.CheckConstraint("ram > 0", name=op.f("ck_workspaces_ram_positive")),
        sa.ForeignKeyConstraint(
            ["image_id"],
            ["template_images.id"],
            name=op.f("fk_workspaces_image_id_template_images"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["instance_id"],
            ["instances.id"],
            name=op.f("fk_workspaces_instance_id_instances"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["job_executions.id"],
            name=op.f("fk_workspaces_job_id_job_executions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
            name=op.f("fk_workspaces_member_id_members"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["templates.id"],
            name=op.f("fk_workspaces_template_id_templates"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workspaces")),
    )
    op.create_index(op.f("ix_workspaces_image_id"), "workspaces", ["image_id"], unique=False)
    op.create_index(op.f("ix_workspaces_instance_id"), "workspaces", ["instance_id"], unique=False)
    op.create_index(op.f("ix_workspaces_job_id"), "workspaces", ["job_id"], unique=False)
    op.create_index(op.f("ix_workspaces_member_id"), "workspaces", ["member_id"], unique=False)
    op.create_index(op.f("ix_workspaces_template_id"), "workspaces", ["template_id"], unique=False)
    op.create_index(
        "uq_workspaces_instance_name_ci",
        "workspaces",
        ["instance_id", sa.literal_column("lower(name)")],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop the complete CoderManager schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_workspaces_instance_name_ci", table_name="workspaces")
    op.drop_index(op.f("ix_workspaces_template_id"), table_name="workspaces")
    op.drop_index(op.f("ix_workspaces_member_id"), table_name="workspaces")
    op.drop_index(op.f("ix_workspaces_job_id"), table_name="workspaces")
    op.drop_index(op.f("ix_workspaces_instance_id"), table_name="workspaces")
    op.drop_index(op.f("ix_workspaces_image_id"), table_name="workspaces")
    op.drop_table("workspaces")
    op.drop_index(op.f("ix_members_instance_id"), table_name="members")
    op.drop_table("members")
    op.drop_table("instance_kubernetes")
    op.drop_index(op.f("ix_database_allocations_database_id"), table_name="database_allocations")
    op.drop_table("database_allocations")
    op.drop_index(op.f("ix_template_images_template_id"), table_name="template_images")
    op.drop_table("template_images")
    op.drop_index(op.f("ix_instances_job_id"), table_name="instances")
    op.drop_index(op.f("ix_instances_application"), table_name="instances")
    op.drop_table("instances")
    op.drop_index(
        "uq_templates_global_name_ci",
        table_name="templates",
        postgresql_where=sa.text("scope = 'global'"),
        sqlite_where=sa.text("scope = 'global'"),
    )
    op.drop_index(
        "uq_templates_application_name_ci",
        table_name="templates",
        postgresql_where=sa.text("scope = 'application'"),
        sqlite_where=sa.text("scope = 'application'"),
    )
    op.drop_index(op.f("ix_templates_application"), table_name="templates")
    op.drop_table("templates")
    op.drop_index("ix_job_executions_retry", table_name="job_executions")
    op.drop_table("job_executions")
    op.drop_index("uq_databases_name_ci", table_name="databases")
    op.drop_table("databases")
    for enum_name in (
        "instance_environment",
        "instance_status",
        "job_status",
        "member_role",
        "member_status",
        "template_scope",
        "workspace_status",
    ):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
