"""rename template names

Revision ID: 20260724_0003
Revises: 20260724_0002
Create Date: 2026-07-24 12:58:04.080942
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260724_0003"
down_revision: str | None = "20260724_0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Rename display and technical names without copying template data."""

    # ### commands auto generated by Alembic - please adjust! ###
    for index_name in (
        "uq_templates_application_name_ci",
        "uq_templates_global_name_ci",
        "uq_templates_application_coder_name_ci",
        "uq_templates_global_coder_name_ci",
    ):
        op.drop_index(index_name, table_name="templates")
    for constraint_name in (
        op.f("ck_templates_name_not_empty"),
        op.f("ck_templates_coder_name_not_empty"),
        op.f("ck_templates_coder_name_normalized"),
    ):
        op.drop_constraint(constraint_name, "templates", type_="check")

    op.alter_column(
        "templates",
        "name",
        new_column_name="display_name",
        existing_type=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "templates",
        "coder_name",
        new_column_name="name",
        existing_type=sa.VARCHAR(length=64),
        existing_nullable=False,
    )

    op.create_check_constraint(
        op.f("ck_templates_display_name_not_empty"),
        "templates",
        "length(trim(display_name)) > 0",
    )
    op.create_check_constraint(
        op.f("ck_templates_name_not_empty"),
        "templates",
        "length(trim(name)) > 0",
    )
    op.create_check_constraint(
        op.f("ck_templates_name_normalized"),
        "templates",
        "name = lower(trim(name))",
    )
    op.create_index(
        "uq_templates_application_display_name_ci",
        "templates",
        ["application", sa.literal_column("lower(display_name)")],
        unique=True,
        postgresql_where=sa.text("scope = 'application'"),
        sqlite_where=sa.text("scope = 'application'"),
    )
    op.create_index(
        "uq_templates_global_display_name_ci",
        "templates",
        [sa.literal_column("lower(display_name)")],
        unique=True,
        postgresql_where=sa.text("scope = 'global'"),
        sqlite_where=sa.text("scope = 'global'"),
    )
    op.create_index(
        "uq_templates_application_name_ci",
        "templates",
        ["application", sa.literal_column("lower(name)")],
        unique=True,
        postgresql_where=sa.text("scope = 'application'"),
        sqlite_where=sa.text("scope = 'application'"),
    )
    op.create_index(
        "uq_templates_global_name_ci",
        "templates",
        [sa.literal_column("lower(name)")],
        unique=True,
        postgresql_where=sa.text("scope = 'global'"),
        sqlite_where=sa.text("scope = 'global'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Restore the former name and coder_name column contract."""

    # ### commands auto generated by Alembic - please adjust! ###
    for index_name in (
        "uq_templates_application_name_ci",
        "uq_templates_global_name_ci",
        "uq_templates_application_display_name_ci",
        "uq_templates_global_display_name_ci",
    ):
        op.drop_index(index_name, table_name="templates")
    for constraint_name in (
        op.f("ck_templates_display_name_not_empty"),
        op.f("ck_templates_name_not_empty"),
        op.f("ck_templates_name_normalized"),
    ):
        op.drop_constraint(constraint_name, "templates", type_="check")

    op.alter_column(
        "templates",
        "name",
        new_column_name="coder_name",
        existing_type=sa.VARCHAR(length=64),
        existing_nullable=False,
    )
    op.alter_column(
        "templates",
        "display_name",
        new_column_name="name",
        existing_type=sa.VARCHAR(length=255),
        existing_nullable=False,
    )

    op.create_check_constraint(
        op.f("ck_templates_name_not_empty"),
        "templates",
        "length(trim(name)) > 0",
    )
    op.create_check_constraint(
        op.f("ck_templates_coder_name_not_empty"),
        "templates",
        "length(trim(coder_name)) > 0",
    )
    op.create_check_constraint(
        op.f("ck_templates_coder_name_normalized"),
        "templates",
        "coder_name = lower(trim(coder_name))",
    )
    op.create_index(
        "uq_templates_application_name_ci",
        "templates",
        ["application", sa.literal_column("lower(name)")],
        unique=True,
        postgresql_where=sa.text("scope = 'application'"),
        sqlite_where=sa.text("scope = 'application'"),
    )
    op.create_index(
        "uq_templates_global_name_ci",
        "templates",
        [sa.literal_column("lower(name)")],
        unique=True,
        postgresql_where=sa.text("scope = 'global'"),
        sqlite_where=sa.text("scope = 'global'"),
    )
    op.create_index(
        "uq_templates_application_coder_name_ci",
        "templates",
        ["application", sa.literal_column("lower(coder_name)")],
        unique=True,
        postgresql_where=sa.text("scope = 'application'"),
        sqlite_where=sa.text("scope = 'application'"),
    )
    op.create_index(
        "uq_templates_global_coder_name_ci",
        "templates",
        [sa.literal_column("lower(coder_name)")],
        unique=True,
        postgresql_where=sa.text("scope = 'global'"),
        sqlite_where=sa.text("scope = 'global'"),
    )
    # ### end Alembic commands ###
