"""add template branch synchronization

Revision ID: 20260724_0002
Revises: 20260724_0001
Create Date: 2026-07-24 12:20:36.849066
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "20260724_0002"
down_revision: str | None = "20260724_0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Add current branch synchronization state without version history."""

    # ### commands auto generated by Alembic - please adjust! ###
    deployment_status = postgresql.ENUM(
        "pending",
        "running",
        "success",
        "error",
        name="template_deployment_status",
    )
    sync_status = postgresql.ENUM(
        "pending",
        "running",
        "success",
        "error",
        name="template_sync_status",
    )
    deployment_status.create(op.get_bind(), checkfirst=True)
    sync_status.create(op.get_bind(), checkfirst=True)
    op.create_table(
        "template_deployments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("template_id", sa.Uuid(), nullable=False),
        sa.Column("instance_id", sa.Uuid(), nullable=False),
        sa.Column("coder_organization_id", sa.Uuid(), nullable=True),
        sa.Column("coder_template_id", sa.Uuid(), nullable=True),
        sa.Column("coder_template_version_id", sa.Uuid(), nullable=True),
        sa.Column("target_commit", sa.String(length=40), nullable=True),
        sa.Column("applied_commit", sa.String(length=40), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "pending",
                "running",
                "success",
                "error",
                name="template_deployment_status",
                create_type=False,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "applied_commit IS NULL OR length(applied_commit) = 40",
            name=op.f("ck_template_deployments_applied_commit_sha"),
        ),
        sa.CheckConstraint(
            "target_commit IS NULL OR length(target_commit) = 40",
            name=op.f("ck_template_deployments_target_commit_sha"),
        ),
        sa.ForeignKeyConstraint(
            ["instance_id"],
            ["instances.id"],
            name=op.f("fk_template_deployments_instance_id_instances"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["templates.id"],
            name=op.f("fk_template_deployments_template_id_templates"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_template_deployments")),
        sa.UniqueConstraint(
            "template_id",
            "instance_id",
            name="uq_template_deployments_template_instance",
        ),
    )
    op.create_index(
        op.f("ix_template_deployments_instance_id"),
        "template_deployments",
        ["instance_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_template_deployments_template_id"),
        "template_deployments",
        ["template_id"],
        unique=False,
    )
    op.add_column("templates", sa.Column("coder_name", sa.String(length=64), nullable=True))
    op.add_column("templates", sa.Column("source_path", sa.String(length=1024), nullable=True))
    op.add_column("templates", sa.Column("branch", sa.String(length=255), nullable=True))
    op.add_column(
        "templates",
        sa.Column("action", sa.String(length=255), server_default="created", nullable=False),
    )
    op.add_column(
        "templates",
        sa.Column(
            "sync_status",
            postgresql.ENUM(
                "pending",
                "running",
                "success",
                "error",
                name="template_sync_status",
                create_type=False,
            ),
            server_default="success",
            nullable=False,
        ),
    )
    op.add_column("templates", sa.Column("job_id", sa.Uuid(), nullable=True))
    op.add_column("templates", sa.Column("step", sa.String(length=255), nullable=True))
    op.execute(
        sa.text(
            "UPDATE templates SET "
            "coder_name = 'template-' || substr(replace(id::text, '-', ''), 1, 12), "
            "source_path = '.', branch = version"
        )
    )
    op.alter_column("templates", "coder_name", nullable=False)
    op.alter_column("templates", "source_path", nullable=False)
    op.alter_column("templates", "branch", nullable=False)
    op.create_check_constraint(
        op.f("ck_templates_coder_name_not_empty"),
        "templates",
        "length(trim(coder_name)) > 0",
    )
    op.create_check_constraint(
        op.f("ck_templates_coder_name_normalized"),
        "templates",
        "coder_name = lower(trim(coder_name))",
    )
    op.create_check_constraint(
        op.f("ck_templates_source_path_not_empty"),
        "templates",
        "length(trim(source_path)) > 0",
    )
    op.create_check_constraint(
        op.f("ck_templates_branch_not_empty"),
        "templates",
        "length(trim(branch)) > 0",
    )
    op.create_check_constraint(
        op.f("ck_templates_action_not_empty"),
        "templates",
        "length(trim(action)) > 0",
    )
    op.create_index(op.f("ix_templates_job_id"), "templates", ["job_id"], unique=False)
    op.create_index(
        "uq_templates_application_coder_name_ci",
        "templates",
        ["application", sa.literal_column("lower(coder_name)")],
        unique=True,
        postgresql_where=sa.text("scope = 'application'"),
        sqlite_where=sa.text("scope = 'application'"),
    )
    op.create_index(
        "uq_templates_global_coder_name_ci",
        "templates",
        [sa.literal_column("lower(coder_name)")],
        unique=True,
        postgresql_where=sa.text("scope = 'global'"),
        sqlite_where=sa.text("scope = 'global'"),
    )
    op.create_foreign_key(
        op.f("fk_templates_job_id_job_executions"),
        "templates",
        "job_executions",
        ["job_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_column("templates", "version")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Restore the former single free-form version field."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "templates",
        sa.Column("version", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    )
    op.execute(sa.text("UPDATE templates SET version = branch"))
    op.alter_column("templates", "version", nullable=False)
    op.create_check_constraint(
        op.f("ck_templates_version_not_empty"),
        "templates",
        "length(trim(version)) > 0",
    )
    op.drop_constraint(
        op.f("fk_templates_job_id_job_executions"),
        "templates",
        type_="foreignkey",
    )
    op.drop_index(
        "uq_templates_global_coder_name_ci",
        table_name="templates",
        postgresql_where=sa.text("scope = 'global'"),
        sqlite_where=sa.text("scope = 'global'"),
    )
    op.drop_index(
        "uq_templates_application_coder_name_ci",
        table_name="templates",
        postgresql_where=sa.text("scope = 'application'"),
        sqlite_where=sa.text("scope = 'application'"),
    )
    op.drop_index(op.f("ix_templates_job_id"), table_name="templates")
    op.drop_column("templates", "step")
    op.drop_column("templates", "job_id")
    op.drop_column("templates", "sync_status")
    op.drop_column("templates", "action")
    op.drop_column("templates", "branch")
    op.drop_column("templates", "source_path")
    op.drop_column("templates", "coder_name")
    op.drop_index(
        op.f("ix_template_deployments_template_id"),
        table_name="template_deployments",
    )
    op.drop_index(
        op.f("ix_template_deployments_instance_id"),
        table_name="template_deployments",
    )
    op.drop_table("template_deployments")
    postgresql.ENUM(name="template_sync_status").drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name="template_deployment_status").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
