"""add instance slugs

Revision ID: 43eaaba4c3ce
Revises: 20260723_0001
Create Date: 2026-07-24 00:44:54.130723
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "43eaaba4c3ce"
down_revision: str | None = "20260723_0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Add nullable globally unique slugs without backfilling historical instances."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("instances", sa.Column("slug", sa.String(length=12), nullable=True))
    op.create_unique_constraint("uq_instances_slug", "instances", ["slug"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Remove the instance slug contract."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_instances_slug", "instances", type_="unique")
    op.drop_column("instances", "slug")
    # ### end Alembic commands ###
