"""initial schema

Revision ID: a868aa80dbea
Revises:
Create Date: 2026-07-30 14:34:33.087450
"""

# ruff: noqa: E501

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a868aa80dbea"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create the complete schema for a fresh Coder Manager database."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "databases",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("instance_max", sa.Integer(), nullable=False),
        sa.Column("host", sa.String(length=255), nullable=False),
        sa.Column("port", sa.Integer(), server_default="5432", nullable=False),
        sa.Column("database_name", sa.String(length=255), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("password_enc", sa.LargeBinary(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("instance_max > 0", name=op.f("ck_databases_instance_max_positive")),
        sa.CheckConstraint(
            "length(trim(database_name)) > 0", name=op.f("ck_databases_database_name_not_empty")
        ),
        sa.CheckConstraint("length(trim(host)) > 0", name=op.f("ck_databases_host_not_empty")),
        sa.CheckConstraint("length(trim(name)) > 0", name=op.f("ck_databases_name_not_empty")),
        sa.CheckConstraint(
            "length(trim(username)) > 0", name=op.f("ck_databases_username_not_empty")
        ),
        sa.CheckConstraint("port >= 1 AND port <= 65535", name=op.f("ck_databases_port_valid")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_databases")),
    )
    op.create_index(
        "uq_databases_name_ci", "databases", [sa.literal_column("lower(name)")], unique=True
    )
    op.create_table(
        "job_executions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("task_name", sa.String(length=255), nullable=False),
        sa.Column("resource_type", sa.String(length=64), nullable=True),
        sa.Column("resource_id", sa.Uuid(), nullable=True),
        sa.Column("step", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "running", "success", "error", name="job_status"),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("attempt", sa.Integer(), server_default="0", nullable=False),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("attempt >= 0", name=op.f("ck_job_executions_attempt_non_negative")),
        sa.CheckConstraint("length(trim(name)) > 0", name=op.f("ck_job_executions_name_not_empty")),
        sa.CheckConstraint("length(trim(step)) > 0", name=op.f("ck_job_executions_step_not_empty")),
        sa.CheckConstraint(
            "length(trim(task_name)) > 0", name=op.f("ck_job_executions_task_name_not_empty")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_executions")),
    )
    op.create_index(
        "ix_job_executions_retry", "job_executions", ["status", "claimed_at"], unique=False
    )
    op.create_table(
        "instances",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("application", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=12), nullable=False),
        sa.Column(
            "environment",
            sa.Enum("development", "staging", "production", name="instance_environment"),
            nullable=False,
        ),
        sa.Column("action", sa.String(length=255), server_default="creating", nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "running", "success", "error", name="instance_status"),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("state", sa.Enum("started", "stopped", name="instance_state"), nullable=False),
        sa.Column("instance_url", sa.String(length=2048), nullable=False),
        sa.Column("password_enc", sa.LargeBinary(), nullable=True),
        sa.Column("argocd_application_name", sa.String(length=63), nullable=True),
        sa.Column("job_id", sa.Uuid(), nullable=True),
        sa.Column("step", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "application = upper(trim(application))",
            name=op.f("ck_instances_application_normalized"),
        ),
        sa.CheckConstraint("length(trim(action)) > 0", name=op.f("ck_instances_action_not_empty")),
        sa.CheckConstraint(
            "length(trim(application)) > 0", name=op.f("ck_instances_application_not_empty")
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["job_executions.id"],
            name=op.f("fk_instances_job_id_job_executions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_instances")),
        sa.UniqueConstraint(
            "application", "environment", name="uq_instances_application_environment"
        ),
        sa.UniqueConstraint(
            "argocd_application_name", name=op.f("uq_instances_argocd_application_name")
        ),
        sa.UniqueConstraint("instance_url", name="uq_instances_instance_url"),
        sa.UniqueConstraint("slug", name="uq_instances_slug"),
    )
    op.create_index(op.f("ix_instances_application"), "instances", ["application"], unique=False)
    op.create_index(op.f("ix_instances_job_id"), "instances", ["job_id"], unique=False)
    op.create_table(
        "templates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("scope", sa.Enum("global", "application", name="template_scope"), nullable=False),
        sa.Column("application", sa.String(length=255), nullable=True),
        sa.Column("git_url", sa.String(length=2048), nullable=False),
        sa.Column("source_path", sa.String(length=1024), nullable=False),
        sa.Column("branch", sa.String(length=255), nullable=False),
        sa.Column("modules", sa.JSON(), nullable=False),
        sa.Column("system_parameter_revision", sa.Integer(), server_default="0", nullable=False),
        sa.Column("action", sa.String(length=255), server_default="created", nullable=False),
        sa.Column(
            "sync_status",
            sa.Enum("pending", "running", "success", "error", name="template_sync_status"),
            server_default="success",
            nullable=False,
        ),
        sa.Column("job_id", sa.Uuid(), nullable=True),
        sa.Column("step", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(scope = 'global' AND application IS NULL) OR (scope = 'application' AND application IS NOT NULL)",
            name=op.f("ck_templates_scope_application_consistent"),
        ),
        sa.CheckConstraint(
            "application IS NULL OR (length(trim(application)) > 0 AND application = upper(trim(application)))",
            name=op.f("ck_templates_application_normalized"),
        ),
        sa.CheckConstraint("length(trim(action)) > 0", name=op.f("ck_templates_action_not_empty")),
        sa.CheckConstraint("length(trim(branch)) > 0", name=op.f("ck_templates_branch_not_empty")),
        sa.CheckConstraint(
            "length(trim(display_name)) > 0", name=op.f("ck_templates_display_name_not_empty")
        ),
        sa.CheckConstraint(
            "length(trim(git_url)) > 0", name=op.f("ck_templates_git_url_not_empty")
        ),
        sa.CheckConstraint("length(trim(name)) > 0", name=op.f("ck_templates_name_not_empty")),
        sa.CheckConstraint(
            "length(trim(source_path)) > 0", name=op.f("ck_templates_source_path_not_empty")
        ),
        sa.CheckConstraint("name = lower(trim(name))", name=op.f("ck_templates_name_normalized")),
        sa.CheckConstraint(
            "system_parameter_revision >= 0",
            name=op.f("ck_templates_system_parameter_revision_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["job_executions.id"],
            name=op.f("fk_templates_job_id_job_executions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_templates")),
    )
    op.create_index(op.f("ix_templates_application"), "templates", ["application"], unique=False)
    op.create_index(op.f("ix_templates_job_id"), "templates", ["job_id"], unique=False)
    op.create_index(
        "uq_templates_application_display_name_ci",
        "templates",
        ["application", sa.literal_column("lower(display_name)")],
        unique=True,
        postgresql_where=sa.text("scope = 'application'"),
        sqlite_where=sa.text("scope = 'application'"),
    )
    op.create_index(
        "uq_templates_application_name_ci",
        "templates",
        ["application", sa.literal_column("lower(name)")],
        unique=True,
        postgresql_where=sa.text("scope = 'application'"),
        sqlite_where=sa.text("scope = 'application'"),
    )
    op.create_index(
        "uq_templates_global_display_name_ci",
        "templates",
        [sa.literal_column("lower(display_name)")],
        unique=True,
        postgresql_where=sa.text("scope = 'global'"),
        sqlite_where=sa.text("scope = 'global'"),
    )
    op.create_index(
        "uq_templates_global_name_ci",
        "templates",
        [sa.literal_column("lower(name)")],
        unique=True,
        postgresql_where=sa.text("scope = 'global'"),
        sqlite_where=sa.text("scope = 'global'"),
    )
    op.create_table(
        "database_allocations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("database_id", sa.Uuid(), nullable=False),
        sa.Column("instance_id", sa.Uuid(), nullable=False),
        sa.Column("schema_name", sa.String(length=63), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(trim(schema_name)) > 0",
            name=op.f("ck_database_allocations_schema_name_not_empty"),
        ),
        sa.ForeignKeyConstraint(
            ["database_id"],
            ["databases.id"],
            name=op.f("fk_database_allocations_database_id_databases"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["instance_id"],
            ["instances.id"],
            name=op.f("fk_database_allocations_instance_id_instances"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_database_allocations")),
        sa.UniqueConstraint(
            "database_id", "schema_name", name="uq_database_allocations_database_schema"
        ),
        sa.UniqueConstraint("instance_id", name="uq_database_allocations_instance_id"),
    )
    op.create_index(
        op.f("ix_database_allocations_database_id"),
        "database_allocations",
        ["database_id"],
        unique=False,
    )
    op.create_table(
        "instance_kubernetes",
        sa.Column("instance_id", sa.Uuid(), nullable=False),
        sa.Column("kubeconfig_enc", sa.LargeBinary(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["instance_id"],
            ["instances.id"],
            name=op.f("fk_instance_kubernetes_instance_id_instances"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("instance_id", name=op.f("pk_instance_kubernetes")),
    )
    op.create_table(
        "members",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("instance_id", sa.Uuid(), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("role", sa.Enum("user", "admin", name="member_role"), nullable=False),
        sa.Column("action", sa.String(length=255), server_default="creating", nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "running", "success", "error", name="member_status"),
            server_default="pending",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("length(trim(action)) > 0", name=op.f("ck_members_action_not_empty")),
        sa.CheckConstraint(
            "length(trim(username)) > 0", name=op.f("ck_members_username_not_empty")
        ),
        sa.CheckConstraint(
            "username = lower(trim(username))", name=op.f("ck_members_username_normalized")
        ),
        sa.ForeignKeyConstraint(
            ["instance_id"],
            ["instances.id"],
            name=op.f("fk_members_instance_id_instances"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_members")),
        sa.UniqueConstraint("instance_id", "username", name="uq_members_instance_username"),
    )
    op.create_index(op.f("ix_members_instance_id"), "members", ["instance_id"], unique=False)
    op.create_table(
        "template_deployments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("template_id", sa.Uuid(), nullable=False),
        sa.Column("instance_id", sa.Uuid(), nullable=False),
        sa.Column("coder_organization_id", sa.Uuid(), nullable=True),
        sa.Column("coder_template_id", sa.Uuid(), nullable=True),
        sa.Column("coder_template_version_id", sa.Uuid(), nullable=True),
        sa.Column("target_commit", sa.String(length=40), nullable=True),
        sa.Column("applied_commit", sa.String(length=40), nullable=True),
        sa.Column("target_system_parameter_revision", sa.Integer(), nullable=True),
        sa.Column("applied_system_parameter_revision", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("pending", "running", "success", "error", name="template_deployment_status"),
            server_default="pending",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "applied_commit IS NULL OR length(applied_commit) = 40",
            name=op.f("ck_template_deployments_applied_commit_sha"),
        ),
        sa.CheckConstraint(
            "applied_system_parameter_revision IS NULL OR applied_system_parameter_revision >= 0",
            name=op.f("ck_template_deployments_applied_system_parameter_revision_non_negative"),
        ),
        sa.CheckConstraint(
            "target_commit IS NULL OR length(target_commit) = 40",
            name=op.f("ck_template_deployments_target_commit_sha"),
        ),
        sa.CheckConstraint(
            "target_system_parameter_revision IS NULL OR target_system_parameter_revision >= 0",
            name=op.f("ck_template_deployments_target_system_parameter_revision_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["instance_id"],
            ["instances.id"],
            name=op.f("fk_template_deployments_instance_id_instances"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["templates.id"],
            name=op.f("fk_template_deployments_template_id_templates"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_template_deployments")),
        sa.UniqueConstraint(
            "template_id", "instance_id", name="uq_template_deployments_template_instance"
        ),
    )
    op.create_index(
        op.f("ix_template_deployments_instance_id"),
        "template_deployments",
        ["instance_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_template_deployments_template_id"),
        "template_deployments",
        ["template_id"],
        unique=False,
    )
    op.create_table(
        "template_images",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("template_id", sa.Uuid(), nullable=False),
        sa.Column("registry", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("version", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(trim(name)) > 0", name=op.f("ck_template_images_name_not_empty")
        ),
        sa.CheckConstraint(
            "length(trim(registry)) > 0", name=op.f("ck_template_images_registry_not_empty")
        ),
        sa.CheckConstraint(
            "length(trim(version)) > 0", name=op.f("ck_template_images_version_not_empty")
        ),
        sa.CheckConstraint(
            "name = lower(trim(name))", name=op.f("ck_template_images_name_normalized")
        ),
        sa.CheckConstraint(
            "registry = lower(trim(registry))", name=op.f("ck_template_images_registry_normalized")
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["templates.id"],
            name=op.f("fk_template_images_template_id_templates"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_template_images")),
        sa.UniqueConstraint(
            "template_id", "registry", "name", "version", name="uq_template_images_reference"
        ),
    )
    op.create_index(
        op.f("ix_template_images_template_id"), "template_images", ["template_id"], unique=False
    )
    op.create_table(
        "template_parameters",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("template_id", sa.Uuid(), nullable=False),
        sa.Column(
            "type", sa.Enum("user", "system", name="template_parameter_type"), nullable=False
        ),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), server_default="", nullable=False),
        sa.Column("required", sa.Boolean(), nullable=True),
        sa.Column("mutable", sa.Boolean(), nullable=True),
        sa.Column("default_value", sa.Text(), nullable=True),
        sa.Column(
            "scope",
            sa.Enum("global", "environment", name="template_parameter_scope"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(type = 'user' AND scope IS NULL AND required IS NOT NULL AND mutable IS NOT NULL) OR (type = 'system' AND scope IS NOT NULL AND required IS NULL AND mutable IS NULL AND default_value IS NULL)",
            name=op.f("ck_template_parameters_type_fields_consistent"),
        ),
        sa.CheckConstraint(
            "length(trim(display_name)) > 0",
            name=op.f("ck_template_parameters_display_name_not_empty"),
        ),
        sa.CheckConstraint(
            "length(trim(name)) > 0", name=op.f("ck_template_parameters_name_not_empty")
        ),
        sa.CheckConstraint(
            "name = lower(trim(name))", name=op.f("ck_template_parameters_name_normalized")
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["templates.id"],
            name=op.f("fk_template_parameters_template_id_templates"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_template_parameters")),
        sa.UniqueConstraint("template_id", "name", name="uq_template_parameters_template_name"),
    )
    op.create_index(
        op.f("ix_template_parameters_template_id"),
        "template_parameters",
        ["template_id"],
        unique=False,
    )
    op.create_table(
        "template_parameter_system_values",
        sa.Column("parameter_id", sa.Uuid(), nullable=False),
        sa.Column(
            "target",
            sa.Enum(
                "global",
                "development",
                "staging",
                "production",
                name="template_parameter_value_target",
            ),
            nullable=False,
        ),
        sa.Column("value_enc", sa.LargeBinary(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parameter_id"],
            ["template_parameters.id"],
            name=op.f("fk_template_parameter_system_values_parameter_id_template_parameters"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "parameter_id", "target", name=op.f("pk_template_parameter_system_values")
        ),
    )
    op.create_table(
        "workspaces",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("instance_id", sa.Uuid(), nullable=False),
        sa.Column("template_id", sa.Uuid(), nullable=False),
        sa.Column("member_id", sa.Uuid(), nullable=False),
        sa.Column("image_id", sa.Uuid(), nullable=False),
        sa.Column("modules", sa.JSON(), nullable=False),
        sa.Column("parameters", sa.JSON(), server_default="{}", nullable=False),
        sa.Column("parameters_revision", sa.Integer(), server_default="0", nullable=False),
        sa.Column("applied_parameters_revision", sa.Integer(), nullable=True),
        sa.Column("coder_workspace_id", sa.Uuid(), nullable=True),
        sa.Column("coder_workspace_build_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=255), server_default="creating", nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "running", "success", "error", name="workspace_status"),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("job_id", sa.Uuid(), nullable=True),
        sa.Column("step", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "applied_parameters_revision IS NULL OR applied_parameters_revision >= 0",
            name=op.f("ck_workspaces_applied_parameters_revision_non_negative"),
        ),
        sa.CheckConstraint("length(name) <= 32", name=op.f("ck_workspaces_name_length")),
        sa.CheckConstraint("length(trim(action)) > 0", name=op.f("ck_workspaces_action_not_empty")),
        sa.CheckConstraint("length(trim(name)) > 0", name=op.f("ck_workspaces_name_not_empty")),
        sa.CheckConstraint(
            "parameters_revision >= 0", name=op.f("ck_workspaces_parameters_revision_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["image_id"],
            ["template_images.id"],
            name=op.f("fk_workspaces_image_id_template_images"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["instance_id"],
            ["instances.id"],
            name=op.f("fk_workspaces_instance_id_instances"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["job_executions.id"],
            name=op.f("fk_workspaces_job_id_job_executions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
            name=op.f("fk_workspaces_member_id_members"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["templates.id"],
            name=op.f("fk_workspaces_template_id_templates"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workspaces")),
    )
    op.create_index(op.f("ix_workspaces_image_id"), "workspaces", ["image_id"], unique=False)
    op.create_index(op.f("ix_workspaces_instance_id"), "workspaces", ["instance_id"], unique=False)
    op.create_index(op.f("ix_workspaces_job_id"), "workspaces", ["job_id"], unique=False)
    op.create_index(op.f("ix_workspaces_member_id"), "workspaces", ["member_id"], unique=False)
    op.create_index(op.f("ix_workspaces_template_id"), "workspaces", ["template_id"], unique=False)
    op.create_index(
        "uq_workspaces_instance_name_ci",
        "workspaces",
        ["instance_id", sa.literal_column("lower(name)")],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop every table and PostgreSQL enum created by the baseline."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_workspaces_instance_name_ci", table_name="workspaces")
    op.drop_index(op.f("ix_workspaces_template_id"), table_name="workspaces")
    op.drop_index(op.f("ix_workspaces_member_id"), table_name="workspaces")
    op.drop_index(op.f("ix_workspaces_job_id"), table_name="workspaces")
    op.drop_index(op.f("ix_workspaces_instance_id"), table_name="workspaces")
    op.drop_index(op.f("ix_workspaces_image_id"), table_name="workspaces")
    op.drop_table("workspaces")
    op.drop_table("template_parameter_system_values")
    op.drop_index(op.f("ix_template_parameters_template_id"), table_name="template_parameters")
    op.drop_table("template_parameters")
    op.drop_index(op.f("ix_template_images_template_id"), table_name="template_images")
    op.drop_table("template_images")
    op.drop_index(op.f("ix_template_deployments_template_id"), table_name="template_deployments")
    op.drop_index(op.f("ix_template_deployments_instance_id"), table_name="template_deployments")
    op.drop_table("template_deployments")
    op.drop_index(op.f("ix_members_instance_id"), table_name="members")
    op.drop_table("members")
    op.drop_table("instance_kubernetes")
    op.drop_index(op.f("ix_database_allocations_database_id"), table_name="database_allocations")
    op.drop_table("database_allocations")
    op.drop_index(
        "uq_templates_global_name_ci",
        table_name="templates",
        postgresql_where=sa.text("scope = 'global'"),
        sqlite_where=sa.text("scope = 'global'"),
    )
    op.drop_index(
        "uq_templates_global_display_name_ci",
        table_name="templates",
        postgresql_where=sa.text("scope = 'global'"),
        sqlite_where=sa.text("scope = 'global'"),
    )
    op.drop_index(
        "uq_templates_application_name_ci",
        table_name="templates",
        postgresql_where=sa.text("scope = 'application'"),
        sqlite_where=sa.text("scope = 'application'"),
    )
    op.drop_index(
        "uq_templates_application_display_name_ci",
        table_name="templates",
        postgresql_where=sa.text("scope = 'application'"),
        sqlite_where=sa.text("scope = 'application'"),
    )
    op.drop_index(op.f("ix_templates_job_id"), table_name="templates")
    op.drop_index(op.f("ix_templates_application"), table_name="templates")
    op.drop_table("templates")
    op.drop_index(op.f("ix_instances_job_id"), table_name="instances")
    op.drop_index(op.f("ix_instances_application"), table_name="instances")
    op.drop_table("instances")
    op.drop_index("ix_job_executions_retry", table_name="job_executions")
    op.drop_table("job_executions")
    op.drop_index("uq_databases_name_ci", table_name="databases")
    op.drop_table("databases")
    for enum_name in (
        "workspace_status",
        "template_parameter_value_target",
        "template_parameter_scope",
        "template_parameter_type",
        "template_deployment_status",
        "member_status",
        "member_role",
        "template_sync_status",
        "template_scope",
        "instance_state",
        "instance_status",
        "instance_environment",
        "job_status",
    ):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
