"""add strict instance state

Revision ID: d3739fe0ca6c
Revises: 0e589bb8796e
Create Date: 2026-07-28 00:04:06.374244
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "d3739fe0ca6c"
down_revision: str | None = "0e589bb8796e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Require an empty instance table and install the strict state contract."""

    # ### commands auto generated by Alembic - please adjust! ###
    instance_count = op.get_bind().scalar(sa.text("SELECT count(*) FROM instances"))
    if instance_count:
        msg = "instances must be empty before upgrading to strict instance state"
        raise RuntimeError(msg)
    instance_state = sa.Enum("started", "stopped", name="instance_state")
    instance_state.create(op.get_bind(), checkfirst=False)
    op.add_column(
        "instances",
        sa.Column(
            "state",
            instance_state,
            nullable=False,
        ),
    )
    op.alter_column(
        "instances",
        "slug",
        existing_type=sa.VARCHAR(length=12),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Remove strict state storage without restoring runtime fallbacks."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "instances",
        "slug",
        existing_type=sa.VARCHAR(length=12),
        nullable=True,
    )
    op.drop_column("instances", "state")
    sa.Enum("started", "stopped", name="instance_state").drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
