"""prepare administrator bootstrap password

Revision ID: f2882be33aab
Revises: 0c9511e7a258
Create Date: 2026-08-23 23:52:51.410788
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "f2882be33aab"
down_revision: str | None = "0c9511e7a258"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Add private durable storage for an unverified bootstrap candidate."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "instances",
        sa.Column("password_candidate_enc", sa.LargeBinary(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop candidate storage only when no ambiguous bootstrap depends on it."""

    op.execute(sa.text("LOCK TABLE instances IN ACCESS EXCLUSIVE MODE"))
    op.execute(
        sa.text(
            """
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1
                    FROM instances
                    WHERE password_candidate_enc IS NOT NULL
                ) THEN
                    RAISE EXCEPTION
                        'Cannot drop administrator bootstrap candidates while any exist';
                END IF;
            END
            $$
            """
        )
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("instances", "password_candidate_enc")
    # ### end Alembic commands ###
