"""replace template scopes with explicit assignments

Revision ID: f891f400b100
Revises: f2882be33aab
Create Date: 2026-08-28 14:28:51.461865
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "f891f400b100"
down_revision: str | None = "f2882be33aab"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Replace inferred template placement with explicit empty assignments."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "template_assignments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("template_id", sa.Uuid(), nullable=False),
        sa.Column("instance_id", sa.Uuid(), nullable=False),
        sa.Column("action", sa.String(length=255), server_default="creating", nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "running", "success", "error", name="template_assignment_status"),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("job_id", sa.Uuid(), nullable=True),
        sa.Column("step", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "action IN ('creating', 'created', 'deleting')",
            name=op.f("ck_template_assignments_action_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["instance_id"],
            ["instances.id"],
            name=op.f("fk_template_assignments_instance_id_instances"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["job_executions.id"],
            name=op.f("fk_template_assignments_job_id_job_executions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["templates.id"],
            name=op.f("fk_template_assignments_template_id_templates"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_template_assignments")),
        sa.UniqueConstraint(
            "template_id", "instance_id", name="uq_template_assignments_template_instance"
        ),
    )
    op.create_index(
        op.f("ix_template_assignments_instance_id"),
        "template_assignments",
        ["instance_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_template_assignments_job_id"), "template_assignments", ["job_id"], unique=False
    )
    op.create_index(
        op.f("ix_template_assignments_template_id"),
        "template_assignments",
        ["template_id"],
        unique=False,
    )
    op.add_column("template_deployments", sa.Column("assignment_id", sa.Uuid(), nullable=False))
    op.drop_index(op.f("ix_template_deployments_instance_id"), table_name="template_deployments")
    op.drop_index(op.f("ix_template_deployments_template_id"), table_name="template_deployments")
    op.drop_constraint(
        op.f("uq_template_deployments_template_instance"), "template_deployments", type_="unique"
    )
    op.create_index(
        op.f("ix_template_deployments_assignment_id"),
        "template_deployments",
        ["assignment_id"],
        unique=True,
    )
    op.drop_constraint(
        op.f("fk_template_deployments_template_id_templates"),
        "template_deployments",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_template_deployments_instance_id_instances"),
        "template_deployments",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_template_deployments_assignment_id_template_assignments"),
        "template_deployments",
        "template_assignments",
        ["assignment_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("template_deployments", "template_id")
    op.drop_column("template_deployments", "instance_id")
    op.drop_index(op.f("ix_templates_application"), table_name="templates")
    op.drop_index(
        op.f("uq_templates_application_display_name_ci"),
        table_name="templates",
        postgresql_where="(scope = 'application'::template_scope)",
    )
    op.drop_index(
        op.f("uq_templates_application_name_ci"),
        table_name="templates",
        postgresql_where="(scope = 'application'::template_scope)",
    )
    op.drop_index(
        op.f("uq_templates_global_display_name_ci"),
        table_name="templates",
        postgresql_where="(scope = 'global'::template_scope)",
    )
    op.drop_index(
        op.f("uq_templates_global_name_ci"),
        table_name="templates",
        postgresql_where="(scope = 'global'::template_scope)",
    )
    op.create_index(
        "uq_templates_name_ci", "templates", [sa.literal_column("lower(name)")], unique=True
    )
    op.drop_constraint(
        op.f("ck_templates_scope_application_consistent"),
        "templates",
        type_="check",
    )
    op.drop_constraint(
        op.f("ck_templates_application_normalized"),
        "templates",
        type_="check",
    )
    op.drop_column("templates", "application")
    op.drop_column("templates", "scope")
    sa.Enum(name="template_scope").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Restore legacy columns and map every current template to global scope."""

    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("global", "application", name="template_scope").create(
        op.get_bind(),
        checkfirst=True,
    )
    op.add_column(
        "templates",
        sa.Column(
            "scope",
            postgresql.ENUM("global", "application", name="template_scope", create_type=False),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "templates",
        sa.Column("application", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    )
    op.execute(sa.text("UPDATE templates SET scope = 'global'"))
    op.alter_column("templates", "scope", nullable=False)
    op.create_check_constraint(
        op.f("ck_templates_application_normalized"),
        "templates",
        "application IS NULL OR (length(trim(application)) > 0 "
        "AND application = upper(trim(application)))",
    )
    op.create_check_constraint(
        op.f("ck_templates_scope_application_consistent"),
        "templates",
        "(scope = 'global' AND application IS NULL) OR "
        "(scope = 'application' AND application IS NOT NULL)",
    )
    op.drop_index("uq_templates_name_ci", table_name="templates")
    op.create_index(
        op.f("uq_templates_global_name_ci"),
        "templates",
        [sa.literal_column("lower(name::text)")],
        unique=True,
        postgresql_where="(scope = 'global'::template_scope)",
    )
    op.create_index(
        op.f("uq_templates_global_display_name_ci"),
        "templates",
        [sa.literal_column("lower(display_name::text)")],
        unique=True,
        postgresql_where="(scope = 'global'::template_scope)",
    )
    op.create_index(
        op.f("uq_templates_application_name_ci"),
        "templates",
        ["application", sa.literal_column("lower(name::text)")],
        unique=True,
        postgresql_where="(scope = 'application'::template_scope)",
    )
    op.create_index(
        op.f("uq_templates_application_display_name_ci"),
        "templates",
        ["application", sa.literal_column("lower(display_name::text)")],
        unique=True,
        postgresql_where="(scope = 'application'::template_scope)",
    )
    op.create_index(op.f("ix_templates_application"), "templates", ["application"], unique=False)
    op.add_column(
        "template_deployments",
        sa.Column("instance_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "template_deployments",
        sa.Column("template_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.execute(
        sa.text(
            """
            UPDATE template_deployments AS deployment
            SET template_id = assignment.template_id,
                instance_id = assignment.instance_id
            FROM template_assignments AS assignment
            WHERE deployment.assignment_id = assignment.id
            """
        )
    )
    op.alter_column("template_deployments", "template_id", nullable=False)
    op.alter_column("template_deployments", "instance_id", nullable=False)
    op.drop_constraint(
        op.f("fk_template_deployments_assignment_id_template_assignments"),
        "template_deployments",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_template_deployments_instance_id_instances"),
        "template_deployments",
        "instances",
        ["instance_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_template_deployments_template_id_templates"),
        "template_deployments",
        "templates",
        ["template_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(op.f("ix_template_deployments_assignment_id"), table_name="template_deployments")
    op.create_unique_constraint(
        op.f("uq_template_deployments_template_instance"),
        "template_deployments",
        ["template_id", "instance_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("ix_template_deployments_template_id"),
        "template_deployments",
        ["template_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_template_deployments_instance_id"),
        "template_deployments",
        ["instance_id"],
        unique=False,
    )
    op.drop_column("template_deployments", "assignment_id")
    op.drop_index(op.f("ix_template_assignments_template_id"), table_name="template_assignments")
    op.drop_index(op.f("ix_template_assignments_job_id"), table_name="template_assignments")
    op.drop_index(op.f("ix_template_assignments_instance_id"), table_name="template_assignments")
    op.drop_table("template_assignments")
    sa.Enum(name="template_assignment_status").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
