"""add instance admin password

Revision ID: fefe7966cbab
Revises: 43eaaba4c3ce
Create Date: 2026-07-24 01:32:41.927881
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "fefe7966cbab"
down_revision: str | None = "43eaaba4c3ce"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

instances = sa.table(
    "instances",
    sa.column("id", sa.Uuid()),
    sa.column("password_enc", sa.LargeBinary()),
)


def upgrade() -> None:
    """Add encrypted instance administrator passwords."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("instances", sa.Column("password_enc", sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Refuse to discard prepared credentials, then remove the column."""

    connection = op.get_bind()
    prepared_password = connection.scalar(
        sa.select(instances.c.id).where(instances.c.password_enc.is_not(None)).limit(1)
    )
    if prepared_password is not None:
        msg = "Cannot remove instance admin passwords while encrypted passwords exist"
        raise RuntimeError(msg)

    op.drop_column("instances", "password_enc")
